name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.8-slim

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        AWS_DEFAULT_REGION: ap-southeast-1
      run: |
        coverage run -m unittest discover
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.4
      env:
        CODECOV_ENV: github-actions
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml