name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    runs-on: ubuntu-latest
    environment: deploy-manual
    steps:
    - uses: actions/checkout@v4
    - name: Deploy with cloudformation
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws cloudformation package --template-file template.yml --output-template-file serverless-output.yaml --s3-bucket ${{ secrets.AWS_S3_BUCKET }}
        aws cloudformation deploy --template-file serverless-output.yaml --stack-name ${{ secrets.STACK_NAME }} --capabilities CAPABILITY_NAMED_IAM --no-execute-changeset